-- シーケンス: SEQ_STEP
IF NOT EXISTS (SELECT * FROM SYS.SEQUENCES WHERE NAME = 'SEQ_STEP')
CREATE SEQUENCE SEQ_STEP START WITH 200001 INCREMENT BY 1;

-- テーブル: STEP
IF NOT EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'STEP')
CREATE TABLE STEP (
	ID INT PRIMARY KEY DEFAULT NEXT VALUE FOR SEQ_STEP,
	NAME NVARCHAR(100) NOT NULL,
	BAT_PATH NVARCHAR(512) NOT NULL,
	MEMO NVARCHAR(1000),
	IS_DELETED BIT DEFAULT 0
);


-- シーケンス: SEQ_WORKFLOW
IF NOT EXISTS (SELECT * FROM SYS.SEQUENCES WHERE NAME = 'SEQ_WORKFLOW')
CREATE SEQUENCE SEQ_WORKFLOW START WITH 100001 INCREMENT BY 1;

-- テーブル: WORKFLOW
IF NOT EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'WORKFLOW')
CREATE TABLE WORKFLOW (
	ID INT PRIMARY KEY DEFAULT NEXT VALUE FOR SEQ_WORKFLOW,
	NAME NVARCHAR(100) NOT NULL,
	FLOW_JSON NVARCHAR(MAX) NOT NULL,
	MEMO NVARCHAR(1000),
	IS_DELETED BIT DEFAULT 0,
	CREATED_AT DATETIME2 DEFAULT GETDATE(),
	UPDATED_AT DATETIME2 DEFAULT GETDATE()
);

-- シーケンス: SEQ_EXECUTION_LOG
IF NOT EXISTS (SELECT * FROM SYS.SEQUENCES WHERE NAME = 'SEQ_EXECUTION_LOG')
CREATE SEQUENCE SEQ_EXECUTION_LOG START WITH 500001 INCREMENT BY 1;

-- テーブル: STEP_EXECUTION_LOG
IF NOT EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'STEP_EXECUTION_LOG')
CREATE TABLE STEP_EXECUTION_LOG (
	ID INT PRIMARY KEY DEFAULT NEXT VALUE FOR SEQ_EXECUTION_LOG,
	WORKFLOW_ID INT NOT NULL,
	STEP_ID INT NOT NULL,
	STATUS NVARCHAR(20),
	STARTED_AT DATETIME2,
	ED_AT DATETIME2,
	EXIT_CODE INT,
	LOG_PATH NVARCHAR(512),
	ERROR_MESSAGE NVARCHAR(MAX),
	FOREIGN KEY (WORKFLOW_ID) REFERENCES WORKFLOW(ID),
	FOREIGN KEY (STEP_ID) REFERENCES STEP(ID)
);

-- シーケンス: SEQ_POST
IF NOT EXISTS (SELECT * FROM SYS.SEQUENCES WHERE NAME = 'SEQ_POST')
CREATE SEQUENCE SEQ_POST START WITH 700001 INCREMENT BY 1;

-- テーブル: POST
IF NOT EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'POST')
CREATE TABLE POST (
	ID INT PRIMARY KEY DEFAULT NEXT VALUE FOR SEQ_POST,
	TITLE NVARCHAR(100) NOT NULL,
	CONTENT NVARCHAR(MAX),
	UPDATED_AT DATETIME NOT NULL DEFAULT GETDATE()
);